version: '3.1'
services:
  app:
    container_name: minesweeper
    image: minesweeper
    build: ./
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_HOST=dbpostgresql
      - POSTGRES_PORT=5432
      - POSTGRES_DB=minesweeper
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    depends_on:
      - dbpostgresql
  dbpostgresql:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=minesweeper
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
