CREATE TABLE games (
        id INT8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        name VARCHAR(255) UNIQUE NOT NULL,
        difficulty VARCHAR(255) NOT NULL,
        state VARCHAR(255) NOT NULL,
        red_flags INT4,
        cells_revealed INT4,
        moves INT4,
        time_played INT8,
        user_id INT8 NOT NULL,
        rows INT4,
        columns INT4,
        mines INT4,
        map JSON,
        CONSTRAINT games_pk PRIMARY KEY (id),
        CONSTRAINT games_users_fk FOREIGN KEY (user_id) REFERENCES users(id)
);