# DataSource Configuration
spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/minesweeper
    username: postgres
    password: admin
    driverClassName: org.postgresql.Driver

# Spring Boot Actuator Configuration
management:
  security.enabled: false
  endpoints:
    web:
      base-path: /
      exposure.include: health
  endpoint:
    health:
      show-details: always