# DataSource Configuration
spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/minesweeper
    username: postgres
    password: admin
    driverClassName: org.postgresql.Driver

  liquibase:
    change-log: classpath:db/changelog/liquibase-changeLog.xml

# Spring Boot Actuator Configuration
management:
  security.enabled: false
  endpoints:
    web:
      base-path: /
      exposure.include: health
  endpoint:
    health:
      show-details: always