# DataSource Configuration
spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  datasource:
    platform: postgres
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driverClassName: org.postgresql.Driver

  liquibase:
    change-log: classpath:db/changelog/liquibase-changeLog.xml

hibernate:
  hbm2ddl:
    auto: none

# Spring Boot Actuator Configuration
management:
  security.enabled: false
  endpoints:
    web:
      base-path: /
      exposure.include: health
  endpoint:
    health:
      show-details: always